# Generated by Django 5.2.1 on 2025-06-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('hint', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(unique=True)),
                ('max_attempts', models.IntegerField(default=7)),
                ('hint_attempt', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='SezWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('hint', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(unique=True)),
                ('max_attempts', models.IntegerField(default=7)),
                ('hint_attempt', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=128)),
                ('guess', models.CharField(max_length=32)),
                ('attempt_number', models.IntegerField()),
                ('result', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dailyword')),
            ],
        ),
    ]
